### ISSUE TITLE
Connect Sign In Component to Dynamic Navbar

### ISSUE THREAD

**Issue by medetcandiler** [202303-PRM-TR-FEW/crowdfunding-app-team-9#12]
**Description:**
Implement the functionality to connect the Sign In component to the dynamic navigation bar. The Sign In button on the navbar should open the Sign In box. Additionally, make the following enhancements:

**Tasks:**
- [x] Connect the Sign In button on the navbar to open the Sign In component.
- [x] Update the name of the Sign Up component to Sign In component.
- [x] Connect the `showSignInBox` state to Redux for managing the visibility of the Sign In box.
- [x] Add a close icon to the close button of the Sign In component for better user experience.
