### ISSUE TITLE
Set up Firebase Authentication and Connect to Dynamic Navbar

### ISSUE THREAD

**Issue by medetcandiler** [202303-PRM-TR-FEW/crowdfunding-app-team-9#16]
### Description:
Implement Firebase authentication and connect it to the dynamic navbar. Details for the task are as follows:

### Tasks:
- [ ] Connect Firebase Authentication to the project.
- [ ] Create the necessary functions and components to handle user sign-in and sign-up using Firebase Auth.
- [ ] Update the existing Sign Up page to integrate with Firebase Auth for user registration.
- [ ] After successful sign-in or sign-up, automatically redirect the user to the homepage with the appropriate Navbar header based on the user's authentication status.

### Additional Notes:
- Try to retrieve the user's profile image and username from Firebase Authentication.
- Use the retrieved user data to personalize the dynamic navbar and enhance the user experience.
