### ISSUE TITLE
 Implement Testimonials Section Component

### ISSUE THREAD

**Issue by medetcandiler** [202303-PRM-TR-FEW/crowdfunding-app-team-9#2]
## Description
Create a Testimonials Section component with a grid system to showcase customer testimonials. The component should dynamically adjust the number of columns based on the screen size.

## Tasks
- [ ] Write JSX structure and CSS styles for the Testimonials Section component.
- [ ] Create a child component named "Testimonial" and utilize it to render the testimonials dynamically.
- [ ] Implement a responsive grid system with different column settings for small, medium, and larger screens.
- [ ] Apply the following tailwind utilities to the main container element: `container`, `mx-auto`, and `px-4` for consistent design.
- [ ] Utilize custom tailwind color utilities exclusively.

## Additional Notes
To incorporate realistic testimonials from users, we have updated the testimonials array as follows:

```javascript
const testimonials = [
  {
    id: 1,
    content: "This crowdfunding platform is amazing! It provides a seamless experience for project creators and backers. I was able to raise funds for my artistic project and connect with a supportive community.",
    author: "Sarah Thompson",
    profession: "Artist",
    image: "https://via.placeholder.com/150/9E5A9D/FFFFFF?text=ST",
  },
  {
    id: 2,
    content: "I'm impressed with the transparency and impact-driven focus of this crowdfunding platform. It helped my nonprofit organization raise funds for a social cause and engage with passionate supporters.",
    author: "David Miller",
    profession: "Nonprofit Founder",
    image: "https://via.placeholder.com/150/FF7F50/FFFFFF?text=DM",
  },
  {
    id: 3,
    content: "As an entrepreneur, I found this platform to be invaluable. It connected me with potential backers who believed in my innovative project. The user-friendly interface made the fundraising process smooth and efficient.",
    author: "Emily Anderson",
    profession: "Entrepreneur",
    image: "https://via.placeholder.com/150/008080/FFFFFF?text=EA",
  },
];
